"""Add mood and update symptoms column in daily_moods

Revision ID: 9194605b3c8f
Revises: 
Create Date: 2025-08-31 13:34:01.313675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9194605b3c8f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_moods', sa.Column('mood', sa.String(), nullable=True))
    op.add_column('daily_moods', sa.Column('symptoms', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_moods', 'symptoms')
    op.drop_column('daily_moods', 'mood')
    # ### end Alembic commands ###
