"""Add model_type to user_models table

Revision ID: ad9954c8728d
Revises: 9194605b3c8f
Create Date: 2025-08-31 13:39:24.274955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad9954c8728d'
down_revision: Union[str, Sequence[str], None] = '9194605b3c8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_models', sa.Column('model_type', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_models', 'model_type')
    # ### end Alembic commands ###
